### ISSUE TITLE
ARC CDN with plugin not working

### ISSUE THREAD

**Issue by filliravaz** [Arc-io/Widget-WordPress-Plugin#1]
Hello, I have the latest version of both WordPress and the plugin, but if I'm on the site, it doesn't show up in the dashboard (even using a phone on mobile data)
I'm sure I have inserted the correct ID
I'm sure I have added the correct domain to the ARC portal

How can I fix this issue? Or is it a problem with the plugin itsef? In case, how can I add ARC manually with a CMS like wordpress?

**Comment by gruns** [comment]
Hi filliravaz! Thank you for your issue!

Let's figure out what's going on.

> Hello, I have the latest version of both WordPress and the plugin

What version of WP are you running?

**Comment by gruns** [comment]
Following up, what's your WP website? I want to take a look.

If you'd prefer not to divulge your website publicly here in this GitHub issue, please email it to us at your.friends@arc.io.

Thank you!

**Comment by filliravaz** [comment]
I'm running WP 5.6, the latest afaik.
Well, the website is a prototype. The short address is *********** (I'm going to remove this at issue solved)
Also, WP says the plugin is version 1.1.8, and that's the same that there is on the website. (Sorry poor grammar, non English keyboard on my phone)

**Comment by gruns** [comment]
Hi filliravaz!

I took a look. Everything looks good to me.

Do you see live widgets appear on your site(s) now? If not, try

  1) Closing all other tabs running Arc (e.g. https://arc.io) so your
     site (e.g. https://qcby.ml/) is the only tab in your browser with
     Arc.

and/or

  2) Opening your site (e.g. https://qcby.ml/) in an incognito tab so
     it's the only tab running Arc in the incognito window.

You should then see yourself as a live widget in the `Live Widget Stats`
card in your portal dashboard and be able to verify that everything is
working correctly.

**Comment by filliravaz** [comment]
works 50-60% of the times. But why do I need to have only a page open?

**Comment by gruns** [comment]
To make sure I understand you correctly with respect to `works 50-60% of the times`, that means when you

  1. Open a new incognito window

and

  2. Open your site in the only tab in that incognito window

that your browser only subsequently appears as a live widget 50-60% of the time, right?

**Comment by filliravaz** [comment]
Yes. I asked some friends to do that, and I can imagine that there is an issue with my internet connection or computer. 
When my friends tried, within 15sec all the website that they were on went active.
However, this seems strange to me, especially since I have a pretty decent connection and computer. I will try some stuff and will report back on what the issue is/was if I find it.

**Comment by filliravaz** [comment]
Yep found the issue. Kaspersky Internet Security was blocking the CDN. I had to add to the exclusions my website and all the other stuff related to ARC.

**Comment by adhe72** [comment]
I have problem with arc.io payment still pending already a few months ago, how can fix it ?

**Comment by filliravaz** [comment]
> I have problem with arc.io payment still pending already a few months ago, how can fix it ?

This is no way relevant to the issue in question. Contact support through official means (email).

**Comment by adhe72** [comment]
I have sent email several times but no response

**Comment by filliravaz** [comment]
Again, this is a GitHub repository meant for the Arc CDN WordPress plugin. No customer support will be done here except for issues with the WordPress Plugin. 
I'm not support for ARC, especially not payment support.

**Comment by adhe72** [comment]
where should i go?
in this comment there is a team from arc.io

**Comment by filliravaz** [comment]
Not on GitHub, that's for sure.
